import turtle
import math
z=turtle.Turtle()
z.color('yellow')
z.shape('circle')
z.goto(0,10)

a=turtle.Turtle()
a.shape('circle')
a.color('blue')
a.penup()
a.goto(0,-40)
a.pendown()
a.speed(0)

b=turtle.Turtle()
b.shape('circle')
b.color('green')
b.penup()
b.goto(0,-60)
b.pendown()
b.speed(7)

c=turtle.Turtle()
c.shape('circle')
c.color('red')
c.penup()
c.goto(0,-80)
c.pendown()
c.speed(6)

d=turtle.Turtle()
d.shape('circle')
d.color('black')
d.penup()
d.goto(0,-100)
d.pendown()
d.speed(5)

e=turtle.Turtle()
e.shape('circle')
e.color('orange')
e.penup()
e.goto(0,-120)
e.pendown()
e.speed(4)

f=turtle.Turtle()
f.shape('circle')
f.color('purple')
f.penup()
f.goto(0,-140)
f.pendown()
f.speed(3)
for i in range(100**10):
    a.goto(-60*math.sin(math.pi/90*i),-40*math.cos(math.pi/90*i))
    b.goto(-80*math.sin(math.pi/100*i),-60*math.cos(math.pi/100*i))
    c.goto(-100*math.sin(math.pi/110*i),-80*math.cos(math.pi/110*i))
    d.goto(-120*math.sin(math.pi/120*i),-100*math.cos(math.pi/120*i))
    e.goto(-140*math.sin(math.pi/130*i),-120*math.cos(math.pi/130*i))
    f.goto(-160*math.sin(math.pi/140*i),-140*math.cos(math.pi/140*i))
